site_name: Gemini Enterprise Agent Repository
site_description: Production-ready Gemini agents for Google Cloud customers.
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
